Update export to simplify multilingual cases
ClickAndMortar/AdvancedCsvConnectorBundle pull request #3
Opened 2018-05-21 15:41 UTC by pierre-marchand

2018-05-22 08:30 UTC, simoncarre requested changes

2018-05-22 08:30 UTC, simoncarre commented on Writer/File/Csv/ProductAdvancedWriter.php
> +    const DEFAULT_LOCALE = 'fr_FR';
L'idéal serait de le définir en le passant en paramètre au service pour pouvoir le modifier en fonction du projet.

2018-05-22 08:30 UTC, simoncarre commented on Writer/File/Csv/ProductAdvancedWriter.php
> +                if ($option->getAttribute()->getLabel() == sprintf('[%s]', $attributeKey)) {
L'idéal serait de faire ça directement au moment de la requête pour limiter les résultats (attention aussi à ne pas faire de condition sur le libellé de l'attribut mais bien son code).
Tu peux créer un nouveau repository "custom" pour les options d'atrributs et te baser sur la méthode `findCodesByIdentifiers` de la classe `AttributeOptionRepository` pour récupérer les options liées à un attribut.

2018-05-22 08:31 UTC, simoncarre commented
@pierre-marchand : N'oublie pas de mettre à jour le fichier `README` avec ces nouvelles possibilités aussi :+1:

2018-05-22 15:44 UTC, pierre-marchand commented
@simoncarre

2018-05-23 09:08 UTC, simoncarre requested changes

2018-05-23 09:08 UTC, simoncarre commented on Resources/config/repositories.yml
> +    candm_advanced_csv_connector.repository.attribute_option.class: ClickAndMortar\AdvancedCsvConnectorBundle\Doctrine\ORM\Repository\AttributeOptionRepository
Tu peux faire plus simple en modifiant simplement la classe définie par Akeneo normalement :

`pim_catalog.repository.attribute_option.class: ClickAndMortar\AdvancedCsvConnectorBundle\Doctrine\ORM\Repository\AttributeOptionRepository`

Je l'avais fait sur quelques projets.

Si ça ne fonctionne pas, ne change pas le repo natif, créé juste un service avec le tien et passe le au constructeur du writer

2018-05-23 09:08 UTC, simoncarre commented on Resources/config/subscribers.yml
> +parameters:
Et du coup tu n'as plus besoin de tout ça.

2018-05-23 09:35 UTC, merged